/**
 * Drizzle Schema for PayloadCMS v3 with Custom Collections
  *
   * This schema defines the database tables for:
    * - PayloadCMS core (users, authentication)
     * - Custom collections (pages, articles, events)
      *
       * Copy this to your project as drizzle/schema.ts
        * Then run: npm run db:push
         */

         import {
           pgTable,
             serial,
               varchar,
                 text,
                   boolean,
                     timestamp,
                       integer,
                         json,
                           primaryKey,
                             uniqueIndex,
                               index,
                                 foreignKey,
                                   bigint,
                                     numeric,
                                     } from 'drizzle-orm/pg-core';

                                     // ============================================================================
                                     // PAYLOADCMS CORE TABLES
                                     // ============================================================================

                                     /**
                                      * Users table - for admin authentication
                                       * This is the primary table PayloadCMS uses for admin accounts
                                        */
                                        export const users = pgTable(
                                          'users',
                                            {
                                                id: serial('id').primaryKey(),
                                                    email: varchar('email', { length: 255 }).notNull(),
                                                        password: varchar('password', { length: 255 }),
                                                            salt: varchar('salt', { length: 255 }),
                                                                firstName: varchar('firstName', { length: 255 }),
                                                                    lastName: varchar('lastName', { length: 255 }),
                                                                        loginAttempts: integer('loginAttempts'),
                                                                            lockUntil: timestamp('lockUntil'),
                                                                                createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
                                                                                    updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow(),
                                                                                      },
                                                                                        (table) => ({
                                                                                            emailUnique: uniqueIndex('users_email_unique').on(table.email),
                                                                                              })
                                                                                              );

                                                                                              /**
                                                                                               * Payload preferences - UI state and settings
                                                                                                */
                                                                                                export const payload_preferences = pgTable(
                                                                                                  'payload_preferences',
                                                                                                    {
                                                                                                        id: serial('id').primaryKey(),
                                                                                                            userId: integer('userId').notNull(),
                                                                                                                key: varchar('key', { length: 255 }).notNull(),
                                                                                                                    value: json('value'),
                                                                                                                        createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
                                                                                                                            updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow(),
                                                                                                                              },
                                                                                                                                (table) => ({
                                                                                                                                    userIdKey: uniqueIndex('payload_preferences_user_key').on(table.userId, table.key),
                                                                                                                                      })
                                                                                                                                      );
                                                                                                                                      
                                                                                                                                      /**
                                                                                                                                       * Locked documents - for draft/publish workflow
                                                                                                                                        */
                                                                                                                                        export const payload_locked_documents = pgTable(
                                                                                                                                          'payload_locked_documents',
                                                                                                                                            {
                                                                                                                                                id: serial('id').primaryKey(),
                                                                                                                                                    globalSlug: varchar('globalSlug', { length: 255 }),
                                                                                                                                                        collectionSlug: varchar('collectionSlug', { length: 255 }),
                                                                                                                                                            docId: integer('docId'),
                                                                                                                                                                fieldName: varchar('fieldName', { length: 255 }),
                                                                                                                                                                    userId: integer('userId').notNull(),
                                                                                                                                                                        createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
                                                                                                                                                                            updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow(),
                                                                                                                                                                              },
                                                                                                                                                                                (table) => ({
                                                                                                                                                                                    idx: uniqueIndex('payload_locked_documents_idx').on(
                                                                                                                                                                                          table.globalSlug,
                                                                                                                                                                                                table.collectionSlug,
                                                                                                                                                                                                      table.docId,
                                                                                                                                                                                                            table.fieldName
                                                                                                                                                                                                                ),
                                                                                                                                                                                                                  })
                                                                                                                                                                                                                  );
                                                                                                                                                                                                                  
                                                                                                                                                                                                                  // ============================================================================
                                                                                                                                                                                                                  // CUSTOM COLLECTIONS
                                                                                                                                                                                                                  // ============================================================================
                                                                                                                                                                                                                  
                                                                                                                                                                                                                  /**
                                                                                                                                                                                                                   * Pages Collection
                                                                                                                                                                                                                    * Main content pages of the school website
                                                                                                                                                                                                                     */
                                                                                                                                                                                                                     export const pages = pgTable(
                                                                                                                                                                                                                       'pages',
                                                                                                                                                                                                                         {
                                                                                                                                                                                                                             id: serial('id').primaryKey(),
                                                                                                                                                                                                                                 title: varchar('title', { length: 255 }).notNull(),
                                                                                                                                                                                                                                     slug: varchar('slug', { length: 255 }).notNull(),
                                                                                                                                                                                                                                         content: text('content'),
                                                                                                                                                                                                                                             description: text('description'),
                                                                                                                                                                                                                                                 featured: boolean('featured').default(false),
                                                                                                                                                                                                                                                     publishedAt: timestamp('publishedAt', { withTimezone: true }),
                                                                                                                                                                                                                                                         createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
                                                                                                                                                                                                                                                             updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow(),
                                                                                                                                                                                                                                                               },
                                                                                                                                                                                                                                                                 (table) => ({
                                                                                                                                                                                                                                                                     slugUnique: uniqueIndex('pages_slug_unique').on(table.slug),
                                                                                                                                                                                                                                                                         slugIdx: index('pages_slug_idx').on(table.slug),
                                                                                                                                                                                                                                                                           })
                                                                                                                                                                                                                                                                           );
                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                           /**
                                                                                                                                                                                                                                                                            * Articles Collection
                                                                                                                                                                                                                                                                             * News, blog posts, and announcements
                                                                                                                                                                                                                                                                              */
                                                                                                                                                                                                                                                                              export const articles = pgTable(
                                                                                                                                                                                                                                                                                'articles',
                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                      id: serial('id').primaryKey(),
                                                                                                                                                                                                                                                                                          title: varchar('title', { length: 255 }).notNull(),
                                                                                                                                                                                                                                                                                              slug: varchar('slug', { length: 255 }).notNull(),
                                                                                                                                                                                                                                                                                                  content: text('content'),
                                                                                                                                                                                                                                                                                                      excerpt: text('excerpt'),
                                                                                                                                                                                                                                                                                                          author: varchar('author', { length: 255 }),
                                                                                                                                                                                                                                                                                                              category: varchar('category', { length: 100 }),
                                                                                                                                                                                                                                                                                                                  featured: boolean('featured').default(false),
                                                                                                                                                                                                                                                                                                                      publishedAt: timestamp('publishedAt', { withTimezone: true }),
                                                                                                                                                                                                                                                                                                                          createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
                                                                                                                                                                                                                                                                                                                              updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow(),
                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                  (table) => ({
                                                                                                                                                                                                                                                                                                                                      slugIdx: index('articles_slug_idx').on(table.slug),
                                                                                                                                                                                                                                                                                                                                          publishedIdx: index('articles_published_idx').on(table.publishedAt),
                                                                                                                                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                            /**
                                                                                                                                                                                                                                                                                                                                             * Events Collection
                                                                                                                                                                                                                                                                                                                                              * School events and announcements
                                                                                                                                                                                                                                                                                                                                               */
                                                                                                                                                                                                                                                                                                                                               export const events = pgTable(
                                                                                                                                                                                                                                                                                                                                                 'events',
                                                                                                                                                                                                                                                                                                                                                   {
                                                                                                                                                                                                                                                                                                                                                       id: serial('id').primaryKey(),
                                                                                                                                                                                                                                                                                                                                                           title: varchar('title', { length: 255 }).notNull(),
                                                                                                                                                                                                                                                                                                                                                               slug: varchar('slug', { length: 255 }).notNull(),
                                                                                                                                                                                                                                                                                                                                                                   description: text('description'),
                                                                                                                                                                                                                                                                                                                                                                       startDate: timestamp('startDate', { withTimezone: true }).notNull(),
                                                                                                                                                                                                                                                                                                                                                                           endDate: timestamp('endDate', { withTimezone: true }),
                                                                                                                                                                                                                                                                                                                                                                               location: varchar('location', { length: 255 }),
                                                                                                                                                                                                                                                                                                                                                                                   category: varchar('category', { length: 100 }),
                                                                                                                                                                                                                                                                                                                                                                                       published: boolean('published').default(false),
                                                                                                                                                                                                                                                                                                                                                                                           createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
                                                                                                                                                                                                                                                                                                                                                                                               updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow(),
                                                                                                                                                                                                                                                                                                                                                                                                 },
                                                                                                                                                                                                                                                                                                                                                                                                   (table) => ({
                                                                                                                                                                                                                                                                                                                                                                                                       startDateIdx: index('events_start_date_idx').on(table.startDate),
                                                                                                                                                                                                                                                                                                                                                                                                           publishedIdx: index('events_published_idx').on(table.published),
                                                                                                                                                                                                                                                                                                                                                                                                             })
                                                                                                                                                                                                                                                                                                                                                                                                             );
                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                             /**
                                                                                                                                                                                                                                                                                                                                                                                                              * Media/Files Collection
                                                                                                                                                                                                                                                                                                                                                                                                               * Images and documents uploaded via PayloadCMS
                                                                                                                                                                                                                                                                                                                                                                                                                */
                                                                                                                                                                                                                                                                                                                                                                                                                export const media = pgTable(
                                                                                                                                                                                                                                                                                                                                                                                                                  'media',
                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                        id: serial('id').primaryKey(),
                                                                                                                                                                                                                                                                                                                                                                                                                            filename: varchar('filename', { length: 255 }).notNull(),
                                                                                                                                                                                                                                                                                                                                                                                                                                mimeType: varchar('mimeType', { length: 100 }),
                                                                                                                                                                                                                                                                                                                                                                                                                                    filesize: integer('filesize'),
                                                                                                                                                                                                                                                                                                                                                                                                                                        width: integer('width'),
                                                                                                                                                                                                                                                                                                                                                                                                                                            height: integer('height'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                url: varchar('url', { length: 512 }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                    alt: text('alt'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                        description: text('description'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                            createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                updatedAt: timestamp('updatedAt', { withTimezone: true }).notNull().defaultNow(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    (table) => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        urlIdx: index('media_url_idx').on(table.url),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // ============================================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // SUPPORT TABLES
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // ============================================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * Breadcrumbs - for navigation context
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export const breadcrumbs = pgTable('breadcrumbs', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              id: serial('id').primaryKey(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                collectionSlug: varchar('collectionSlug', { length: 255 }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  docId: integer('docId'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    url: varchar('url', { length: 512 }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      label: varchar('label', { length: 255 }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * Rels (Relations) - for relationship fields in PayloadCMS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * Handles many-to-many relationships between documents
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           export const rels = pgTable(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'rels',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   id: serial('id').primaryKey(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       collectionFrom: varchar('collectionFrom', { length: 255 }).notNull(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           collectionTo: varchar('collectionTo', { length: 255 }).notNull(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               docFromId: integer('docFromId').notNull(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   docToId: integer('docToId').notNull(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       position: integer('position'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           createdAt: timestamp('createdAt', { withTimezone: true }).notNull().defaultNow(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               (table) => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   idx: uniqueIndex('rels_idx').on(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         table.collectionFrom,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               table.collectionTo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     table.docFromId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           table.docToId
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // ============================================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // EXPORT ALL TABLES
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // ============================================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 export const allTables = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // Core
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     users,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       payload_preferences,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         payload_locked_documents,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // Collections
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             pages,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               articles,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 events,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   media,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // Support
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       breadcrumbs,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         rels,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         export default allTables;
